// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkggpfztcmzpsblwhdpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZ2dwZnp0Y216cHNibHdoZHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODk2ODUsImV4cCI6MjA2NTA2NTY4NX0.2CmzohLFI5JRp3X_cukW8Sfirvoq8K_vuszRt4w6Co8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);